import { IAppLanguage } from "./interface";

export const APP_ENV = {
  APP_NAME: "React Native Boilerplate",
  APP_VERSION: "1.0.0",
  APP_BUILD: "1",
  APP_ENV: "development",
  APP_AUTHOR: "React Native Boilerplate",
  APP_CONTACT: "680353245",
  APP_WEBSITE: "https://www.gwislab.com",
  APP_PRIVACY_POLICY: "https://www.gwislab.com",
  APP_TERMS_OF_USE: "https://www.gwislab.com",
  APP_LICENSE: "https://www.gwislab.com",
  APP_DESCRIPTION: "React Native Boilerplate",
  APP_DEVELOPER: "Gwislab",
  APP_DEVELOPER_WEBSITE: "https://www.gwislab.com",
  APP_DEVELOPER_EMAIL: "bisynerd@gwislab.com",
  APP_DEVELOPER_PHONE: "680353245",
  APP_DEVELOPER_ADDRESS: "Gwislab",
  APP_DEVELOPER_CITY: "Gwislab",
  APP_DEVELOPER_STATE: "Gwislab",
  APP_DEVELOPER_COUNTRY: "Gwislab",
  APP_DEVELOPER_ZIP_CODE: "Gwislab",
  APP_DEVELOPER_LOGO: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_FACEBOOK: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_TWITTER: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_INSTAGRAM: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_LINKEDIN: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_YOUTUBE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_GITHUB: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_WEBSITE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_EMAIL: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_PHONE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_ADDRESS: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_CITY: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_STATE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_COUNTRY: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_ZIP_CODE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_LOGO: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_PRIVACY_POLICY: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_TERMS_OF_USE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_LICENSE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DESCRIPTION: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_WEBSITE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_EMAIL: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_PHONE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_ADDRESS: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_CITY: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_STATE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_COUNTRY: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_ZIP_CODE: "https://www.gwislab.com",
  APP_DEVELOPER_SOCIAL_DEVELOPER_LOGO: "https://www.gwislab.com",
  APP_DEFAULT_LANGUAGE: "en" as IAppLanguage,
  APP_DEFAULT_COUNTRY: "US",
  APP_DEFAULT_CURRENCY: "USD",
  APP_DEFAULT_TIMEZONE: "America/New_York",
  APP_DEFAULT_THEME: "light",
  APP_DEFAULT_MODE: "light",
  APP_DEFAULT_DIRECTION: "ltr",
  APP_DEFAULT_LAYOUT: "full",
  APP_TEL_PHONE: "680353245"
};
